### ISSUE TITLE
encoding new categories ( present in the train set and not in the train set)

### ISSUE THREAD

**Issue by syrinecheriaa** [dirty-cat/dirty_cat#102]

**Comment by GaelVaroquaux** [comment]
What's the issue/question? 

With similarity encoding, if you gone a new category, it is encoded via its similarity to the know ones.

**Comment by syrinecheriaa** [comment]
with the python library, is there a way to define the "know category" or the prototype ones manually ?
So that we can encode the categories in the test set via their similarities to those in the train set.

**Comment by pcerda** [comment]
The argument "categories" of SimilarityEncoder is exactly made for this. I'm closing the issue.
