### ISSUE TITLE
should examples call plt.show() ?

### ISSUE THREAD

**Issue by jeromedockes** [dirty-cat/dirty_cat#107]
otherwise we never get to see the figures :)

**Comment by GaelVaroquaux** [comment]
> otherwise we never get to see the figures :)

Fine with me.

The reason that they don't is that most people run them in the notebook
:)

**Comment by GaelVaroquaux** [comment]
Most people by a wider majority run this in the notebook, and "plt.show()" makes the docs hard to read for non experts. So I think that we shouldn't bother. Closing this one, thanks @jeromedockes
