### ISSUE TITLE
can't read the data? 

### ISSUE THREAD

**Issue by alla15747** [dirty-cat/dirty_cat#112]
data = pd.read_csv(employee_salaries['./home/azureuser/anaconda/envs/azureml_py36/lib/python3.6/site-packages/dirty_cat/data'])

I give the path in Jupyter Notebook - Run on Azure 

**Error**

The downloaded data contains the employee_salaries dataset.
It can originally be found at: https://catalog.data.gov/dataset/ employee-salaries-2016
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-48-56fc53c6a18d> in <module>
      1 employee_salaries = datasets.fetch_employee_salaries()
      2 print(employee_salaries['description'])
----> 3 data = pd.read_csv(employee_salaries['./home/azureuser/anaconda/envs/azureml_py36/lib/python3.6/site-packages/dirty_cat/data'])
      4 print(data.head(n=5))

KeyError: './home/azureuser/anaconda/envs/azureml_py36/lib/python3.6/site-packages/dirty_cat/data'

​

**Comment by solalatus** [comment]
Sadly at the [URL for download](https://data.montgomerycountymd.gov/api/views/xj3h-s2i7/rows.csv?accessType=DOWNLOAD) one can only find:

`{
  "code" : "authentication_required",
  "error" : true,
  "message" : "You must be logged in to access this resource"
}`

They must have changed policy and do not allow for download now 👎

**Comment by solalatus** [comment]
And by the way: `python3.7/site-packages/dirty_cat/data/open_payments/PGYR13_P011718.ZIP`

<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;132&#46;8e641002&#46;1587572250&#46;7fd9958
</BODY></HTML>

SO sad to say, but this is also broken! :-(

**Comment by GaelVaroquaux** [comment]
@TwsThomas : I think that you fixed that, didn't you?

**Comment by TwsThomas** [comment]
> @TwsThomas : I think that you fixed that, didn't you?

Yes, Now it download employee_salaries from openML.
It should go like this : 
```from dirty_cat.datasets import fetch_employee_salaries
employee_salaries = fetch_employee_salaries()
print(employee_salaries['DESCR'])
df = employee_salaries['data']`

**Comment by GaelVaroquaux** [comment]
I am closing this, as it feels that it no longer applies to the current codebase (the data downloads well)
