### ISSUE TITLE
dirty_cat jaro distance is different from python-Levenshtein package

### ISSUE THREAD

**Issue by alexis-cvetkov** [dirty-cat/dirty_cat#115]
The function test_compare_implementations of test_string_distances.py compares dirty_cat implementation of jaro and jaro_winkler metrics with the python-Levenshtein package.
In practice these 2 implementations are different, but I believe it has never been signaled by Travis since the comparison is done on a small number (N=10) of random strings for which both method returns 0 with very high probability.

Here is a simple code to expose the difference:

```
from dirty_cat import string_distances
import Levenshtein

for s1, s2 in[('acc', 'babbb'), ('acc', 'bbabb'), ('acc', 'bbbab')]:
    print(f'dirty_cat {s1, s2} = {string_distances._jaro_winkler(s1, s2, winkler=False)}')
    print(f'Levenshtein {s1, s2} = {Levenshtein.jaro(s1, s2)}')
    print('-'*50)

>>> dirty_cat ('acc', 'babbb') = 0.5111111111111111
>>> Levenshtein ('acc', 'babbb') = 0.5111111111111111
>>> --------------------------------------------------
>>> dirty_cat ('acc', 'bbabb') = 0.0
>>> Levenshtein ('acc', 'bbabb') = 0.5111111111111111
>>> --------------------------------------------------
>>> dirty_cat ('acc', 'bbbab') = 0.0
>>> Levenshtein ('acc', 'bbbab') = 0.0
>>> --------------------------------------------------
```
From this examples and other tests I've made I believe that the difference lies in the definition of matching characters. The dirty_cat implementation uses the [wikipedia](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance) definition: two characters from s1 and s2 are considered matching only if they are the same and not farther than
`int(max(|s1|,|s2|) / 2) - 1` = 1 in my example.

Instead, the Levensthein implementation seems to use `int( (min(|s1|,|s2|) + 1) / 2)` = 2.

**Comment by GaelVaroquaux** [comment]
Fixed in #116. Thanks!
