### ISSUE TITLE
CircleCI is failing

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#117]
I'm not sure why:
https://circleci.com/gh/dirty-cat/dirty_cat/482

Cc @alexis-cvetkov

**Comment by alexis-cvetkov** [comment]
It seems that we don't have the rights to access the dirty-cat repo on github.
![image](https://user-images.githubusercontent.com/33491786/80589106-df191580-8a19-11ea-9718-7b6e97533f60.png)

A suggested [procedure](https://discuss.circleci.com/t/permission-denied-publickey/31030/2) is to reset webhooks, checkout keys and deploy keys that link dirty-cat to circleci, but admin rights are required on github.

**Comment by alexis-cvetkov** [comment]
Resetting webhooks and adding a deploy key solved the issue, but now CircleCI is failing to build the doc. I opened the PR #118 to fix that.

**Comment by GaelVaroquaux** [comment]
Fixed!! Thanks to you all!
