### ISSUE TITLE
Warning messages in notebook 04_dimension_reduction_and_performance

### ISSUE THREAD

**Issue by amy12xx** [dirty-cat/dirty_cat#140]
Too many ConvergenceWarning messages in the current notebook make it hard to see the actual output. 
https://dirty-cat.github.io/stable/auto_examples/04_dimension_reduction_and_performance.html#sphx-glr-auto-examples-04-dimension-reduction-and-performance-py

**Comment by Phaide** [comment]
Hello @amy12xx,

This is indeed annoying.
One workaround is to use the "max_iter" argument during the LogisticRegression instantiation.
I've submitted PR #141, applying that method. 
Best regards

**Comment by GaelVaroquaux** [comment]
Fixed in #141
