### ISSUE TITLE
Apply minhash_encoder to more than 1024 categories returns -1

### ISSUE THREAD

**Issue by jp-varela** [dirty-cat/dirty_cat#146]
Hy all,
I am trying to apply minhash_encoder to a somewhat large dataset of strings (~200k distinct).
I was testing my code with 10 strings, and it was running fine.
But when I tested using all dataset, most of the strings were represented as all '-1' vectors.
I took a look at the source code and find this line inside 'minhash_encoder.py', that maybe is causing the problem:
`self.hash_dict = LRUDict(capacity=2**10)`
Not sure why this is used, but I checked with 1025 strings, and only the first one returns -1.
This encoder should work with a lot more variables, right?

Code to replicate:
```
from dirty_cat import MinHashEncoder
import random
import string

def get_random_string(length):
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str

# 1024 categories -> all ok
raw_data = [get_random_string(10) for x in range(1024)]
hash_encoder = MinHashEncoder(n_components=10)
transformed_values = hash_encoder.fit_transform(raw_data)
print(transformed_values)

# 1025 categories -> first represented as -1's
raw_data = [get_random_string(10) for x in range(1025)]
hash_encoder = MinHashEncoder(n_components=10)
transformed_values = hash_encoder.fit_transform(raw_data)
print(transformed_values)
```

**Comment by GaelVaroquaux** [comment]
It seems that we indeed have a bug. I thought that the latest changes to
the MinHashEncoder made it robust to cache overflow, but it seems not.
We'll look at this ASAP.

Can you put here the code that you used to demo the bug, it will save us
time. Thank you!

**Comment by amy12xx** [comment]
I tried to replicate using the employee dataset, and using a small cache capacity (=10), but wasn't able to replicate it. An example would indeed be helpful.

**Comment by jp-varela** [comment]
Just edited the issue with code to replicate it.

**Comment by jp-varela** [comment]
@amy12xx I am using version 0.0.7

**Comment by amy12xx** [comment]
Was not able to replicate this on the latest, I am using windows. @Phaide / @GaelVaroquaux may have some luck?

**Comment by Phaide** [comment]
Hi all,
I tried on both Windows 10 and Ubuntu 20.04, and indeed, I get the first line as only -1s using the 1025 strings.
I'm using version 0.0.7 as well.

**Comment by amy12xx** [comment]
Yes, you are correct, I was testing on the master. This is fixed on master (release version 0.0.8)

**Comment by GaelVaroquaux** [comment]
Let's add a test to prevent a regression and release, for the joy of our users!

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by amy12xx** [comment]
sounds good, I can try to do that this weekend.
