### ISSUE TITLE
Deprecation warning in CI

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#159]
Hi

On the [last commit](https://travis-ci.org/github/dirty-cat/dirty_cat/jobs/759337761), the CI raised a `DeprecationWarning` regarding a regular expression:

![image](https://user-images.githubusercontent.com/33222654/108341799-5b176080-71da-11eb-9a95-14ae69b07d57.png)

**Comment by alexis-cvetkov** [comment]
The code for the ci-helpers we use comes from here: https://github.com/astropy/ci-helpers.
Ideally they should fix it, but it seems that the package is no longer actively developed. In the long run we should maybe look for other ci-helpers ?

**Comment by LilianBoulard** [comment]
Not relevant as we don't use Travis anymore
