### ISSUE TITLE
Approach to merge similar categories

### ISSUE THREAD

**Issue by aguinaldoabbj** [dirty-cat/dirty_cat#166]
I've been thinking and testing if wouldn't be convenient to include in _dirty cat_ a function to merge similar categories according to a threshold value?
I'd like to contribute but I really don't know where to start, o what approach to take. Any guiding lights for a small contribution?

**Comment by LilianBoulard** [comment]
Hi @aguinaldoabbj 
Thanks for your interest in dirty_cat !
Sorry for the bummer, but unfortunately, this is outside the scope of what the library is trying to achieve.
If you wish to contribute anyway, issues might be the way to start. Reading the papers and the code can help you better grasp the objective :)
