### ISSUE TITLE
Topic labels that changes over multiple calls of get_feature_names in GapEncoder

### ISSUE THREAD

**Issue by alexis-cvetkov** [dirty-cat/dirty_cat#188]
This is not a problem in itself, but could be an unexpected behaviour. Calling `GapEncoder.get_feature_names()` several times in a row can in rares cases return different labels between calls. This is because `get_feature_names` calls `transform` to encode potential labels and decide which ones are the most relevant for each topic. However `transform` returns slightly different activations H over multiple calls on the same input X, because it keeps the fitted activations H from the previous call to continue the optimization, instead of starting from scratch every time.
These slightly different encodings H can lead to small changes in topic labels.

**Comment by jovan-stojanovic** [comment]
We have failing tests because of this: examples [here](https://github.com/dirty-cat/dirty_cat/actions/runs/3411574522/jobs/5676002539) and [here](https://github.com/dirty-cat/dirty_cat/actions/runs/3427567251/jobs/5710734704).

**Comment by aussetg** [comment]
This is actually quite annoying / problematic for pipelines that use `set_output(transform="pandas")`  as they will invariably fail :)

**Comment by GaelVaroquaux** [comment]
OK, let's prioritize this.
