### ISSUE TITLE
Tune the SuperVectorizer

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#191]
Right now, in our examples, the SuperVectorizer induces a small but present loss in prediction accuracy. We need to investigate whether changing the settings of the SuperVectorizer can fix this.

My hunch is that we should look at:
- The number of components that we use for the default GapEncoder (I suspect that we use too much)
- The cardinality threshold at which we move away from OneHotEncoder (I suspect that it is too low)

We should tune these choices using a few different datasets.

**Comment by LilianBoulard** [comment]
Forgot to tag the issue in the PR, solved by #211
