### ISSUE TITLE
Not able to install the version 0.2.0

### ISSUE THREAD

**Issue by premjithb** [dirty-cat/dirty_cat#204]
I am not able to install the version 0.2.0. I tried the following command to install 

sudo pip3 install -U --user dirty_cat

Output:

Requirement already up-to-date: dirty_cat in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: joblib in /usr/local/lib/python3.6/dist-packages (from dirty_cat)
Requirement already up-to-date: numpy in /usr/local/lib/python3.6/dist-packages (from dirty_cat)
Requirement already up-to-date: scikit-learn>=0.20 in /usr/local/lib/python3.6/dist-packages (from dirty_cat)
Requirement already up-to-date: scipy in /usr/local/lib/python3.6/dist-packages (from dirty_cat)
Requirement already up-to-date: requests in /usr/local/lib/python3.6/dist-packages (from dirty_cat)
Requirement already up-to-date: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.20->dirty_cat)
Requirement already up-to-date: charset-normalizer~=2.0.0; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests->dirty_cat)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->dirty_cat)
Requirement already up-to-date: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->dirty_cat)
Requirement already up-to-date: idna<4,>=2.5; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests->dirty_cat)

But, when I checked the version no, it is printing '0.1.0'

>> import dirty_cat
>> dirty_cat.__version__
'0.1.0'
![Screenshot from 2021-07-26 22-17-49](https://user-images.githubusercontent.com/9291325/126934982-7ebe9567-7865-42ae-a98f-f8eafdc786b4.png)

**Comment by GaelVaroquaux** [comment]
Version 0.2 is not released yet. Only an alpha is released (which means that some things will break or change).

As mentioned on the changelog ( https://dirty-cat.github.io/stable/CHANGES.html ) installing an alpha requires to explicitly ask for prereleases in pip.
