### ISSUE TITLE
Add an handle_unknown parameter for SuperVectorizer.

### ISSUE THREAD

**Issue by LeoGrin** [dirty-cat/dirty_cat#230]
- I think there should be three options {"error", "ignore", "error_strict"}. If "error" or "ignore", this option would be passed to the low_card_cat_transformer. If "error_strict", this would pass the "error" option to both low_card_cat_transformer and high_card_cat_transformer.
- I would use "error" as the default value.

**Comment by GaelVaroquaux** [comment]
Sounds good!

**Comment by LeoGrin** [comment]
Made a PR #235

**Comment by LeoGrin** [comment]
Closing this issue after a discussion in #235 (it's seems simpler to simply set this parameter in the low_card_transformer argument of the SuperVectorizer)
