### ISSUE TITLE
Replace strings which indicates missing values by NaNs  (for SuperVectorizer)

### ISSUE THREAD

**Issue by LeoGrin** [dirty-cat/dirty_cat#231]
I think it would be nice for the SuperVectorizer to convert strings which indicates missing values by NaNs before handling missing values.

Strings I have in mind:

- whitespaces (\s)
- "?"
- "missing"

**Comment by GaelVaroquaux** [comment]
I'm not sure how useful that would be: for categorical data, treating
missing values as a special category is a very good option; and I believe
that the current state of the code will lead to that.

**Comment by LeoGrin** [comment]
I agree for categorical data. I actually encountered this issue when dealing with a column which contained numerical data, entered by users in a survey: the values in the column were strings containing either an integer, or a space. This was breaking Pandas type detection.

**Comment by GaelVaroquaux** [comment]
OK, so it's a type detection problem.

Then I'm fine with the solution, but it should be explained and
documented as relevant for type detection (not in these terms, as they
are not meaningful for most users).

Thanks!!

**Comment by LeoGrin** [comment]
Actually I checked and the type detection problem is more general: pandas function convert_dtypes doesn't infer type from string columns. I've made a new issue #234  and I'm closing this one (as solving #234 should solve this issue at the same time).
