### ISSUE TITLE
Replace columns indexes by columns names in SuperVectorizer.transformers_

### ISSUE THREAD

**Issue by LeoGrin** [dirty-cat/dirty_cat#232]
Right now, the transformers_ attribute of SuperVectorizer contains either the columns names (for low_card_cat_transformer and high_card_cat_transformer) or the columns indexes (for remainder for instance). I think we could use columns names for every transformer., as it would be more readable for users.

**Comment by GaelVaroquaux** [comment]
To make sure that I understand well, can you add an example of the
current sub-optimal behavior?

Thanks!

**Comment by LeoGrin** [comment]
For instance in the [SuperVectorizer example](https://dirty-cat.github.io/stable/auto_examples/01_dirty_categories.html#example-super-vectorizer):

`sup_vec.transformers_`

`[('low_card_cat', OneHotEncoder(), ['gender', 'department', 'department_name', 'assignment_category']), ('high_card_cat', GapEncoder(n_components=30), ['division', 'employee_position_title', 'underfilled_job_title']), ('remainder', 'passthrough', [7])]`

To understand that that column 7 is year_first_hired, you need to go back to your dataframe.

**Comment by GaelVaroquaux** [comment]
OK, +1 for suggested fix.

Thanks!!!

**Comment by LeoGrin** [comment]
Fixed
