### ISSUE TITLE
Handle string in auto_cast (SuperVectorizer)

### ISSUE THREAD

**Issue by LeoGrin** [dirty-cat/dirty_cat#234]
# Suboptimal behavior

Right now the `auto_cast` method from the SuperVectorizer uses the pandas function `convert_dtypes`.

But this function doesn't  try to infer input type from string columns. For instance:

```
import pandas as pd

df = pd.DataFrame({"float_column":["1.3", "4.12", "7.12", "9.12", "1128.12323"],
                   "int_column":["10", "400", "1265", "12", "753"],
                   "bool_column":["true", "false", "true", "false", "false"]})

df = df.convert_dtypes()

for col in df.columns:
    print(df[col].convert_dtypes().dtypes)

```

outputs

```
string
string
string
```

# Use cases

I encountered this problem when dealing with survey data, where people had to enter a number, but some people just entered an empty string. I'm not sure how useful it is in general for the use cases we have in mind.

# Possible solution

We could do something akin to what I suggested in  #233 for dates. For instance, to infer int or float columns, we could use `pd.to_numeric` and check if it worked on enough rows.

**Comment by GaelVaroquaux** [comment]
I think that pandas must have code to do the conversion that you are
looking for, because it does this when loading csvs. Inspecting the code
source of pandas (starting from the read_csv function), might give you a
hint of how to call code from pandas to improve the behavior.
