### ISSUE TITLE
One hot encoding of Supervectorizer for columns with 2 values

### ISSUE THREAD

**Issue by amy12xx** [dirty-cat/dirty_cat#246]
Just something I observed using SuperVectorizer, on a dataset with columns having mostly 2 categorical values. As documented, it runs one hot encoding on them, and this blows up the feature space. This is probably an edge case, and the example I have here is maybe an extreme one. For just two values it seemed excessive to do one-hot encoding.

```
from dirty_cat import SuperVectorizer
from sklearn.datasets import fetch_openml
X, y = fetch_openml("kr-vs-kp", return_X_y=True)
X.shape
(3196, 36)
X.describe()
       bkblk bknwy bkon8 bkona bkspr bkxbq bkxcr bkxwp blxwp bxqsq cntxt dsopp dwipd  ... simpl skach skewr skrxp spcop stlmt thrsk wkcti wkna8 wknck wkovl wkpos wtoeg
count   3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  ...  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196  3196
unique     2     2     2     2     2     2     2     2     2     2     2     2     2  ...     2     2     2     2     2     2     2     2     2     2     2     2     2
top        f     f     f     f     f     f     f     f     f     f     f     f     l  ...     f     f     t     f     f     f     f     f     f     f     t     t     n
freq    2839  2971  3076  2874  2129  1722  2026  2500  1980  2225  1817  2860  2205  ...  1975  3185  2216  3021  3195  3149  3060  2631  3021  1984  2007  2345  2407

[4 rows x 36 columns]

sv = SuperVectorizer()
X_tx = sv.fit_transform(X)
X_tx.shape
(3196, 73)

```

**Comment by LilianBoulard** [comment]
Hello @amy12xx, glad to see you're still active on dirty_cat, and sorry for the delay !
So instead of one-hot encoding, @alexis-cvetkov suggested using a binary encoding, would that be fitting ? WDYT @GaelVaroquaux ?

**Comment by amy12xx** [comment]
yeah, sorry I've been somewhat MIA. Binary encoding is what I ended up doing on this problem.

**Comment by GaelVaroquaux** [comment]
@amy12xx : should we use "drop='first'" rather than "drop='binary'" in the OneHotEncoder, which means that all category encodings have one less feature?

**Comment by GaelVaroquaux** [comment]
After many discussions, including with the scikit-learn team, the consensus is that the interpretability issue is a real concern and that we should rather go for if_binary
