### ISSUE TITLE
`Version` might not work with special versions

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#275]
I worked earlier this week on version comparison, and the `Version` class was implemented in the utils. See #261.

Today I realized that the way it is currently implemented, it will probably raise errors when checking for special versions, such as pre-releases, release candidates, dev versions, and others.
This is because it separates the version based on the dot character, and uses the two first (or only the first) values as the major and minor versions, which it converts to integers.

I tested a few scikit-learn versions (taken from [PyPI](https://pypi.org/project/scikit-learn/#history)), and it seems to work :

To reproduce:
```commandline
$ pip install --upgrade scikit-learn==0.24.dev0
$ python -c "import sklearn; print(sklearn.__version__);"
0.24.dev0

$ pip install --upgrade scikit-learn==1.0rc2
$ python -c "import sklearn; print(sklearn.__version__);"
1.0.rc2

$ pip install --upgrade scikit-learn==1.1.0rc1
$ python -c "import sklearn; print(sklearn.__version__);"
1.1.0rc1
```

If the version returned were to be e.g. `1.0rc1`, the method would raise a `ValueError` because it would try to convert `0rc1` (the minor) to an integer.

Currently, we only use this class to compare versions of scikit-learn, so it shouldn't be a problem for now.
This is however something to look out for in the future !

**Comment by jjerphan** [comment]
scikit-learn defintes [private class to parse versions](https://github.com/scikit-learn/scikit-learn/blob/5efcb10c3e9f87103c404c32a036beb623182c83/sklearn/externals/_packaging/version.py#L280). It might be possible to privately import this class (i.e. `sklearn.externals._packaging.Version` and expose it as a private symbol of `dirty_cat` (e.g `dirty_cat._packaging.Version`) to use in in the code-base.

Would this be useful for this case?

**Comment by GaelVaroquaux** [comment]
This is related to the need to have dev tools in scikit-learn, which are not private, but neither user facing.

I don't remember where we are at in scikit-learn, but we clearly need to invest resources in this.

**Comment by LilianBoulard** [comment]
As mentioned, and briefly implemented in https://github.com/dirty-cat/dirty_cat/pull/355, we could use their `parse_version` function.
