### ISSUE TITLE
Inconsistencies regarding transition from `get_feature_names` to `get_feature_names_out`

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#279]
As part of the work I'm putting in #277, I noticed the way we're handling the usage of `get_feature_names` since the transition to `get_feature_names_out` (sklearn 1.0) is inconsistent.

For example, in the `GapEncoder` and the `SuperVectorizer`, we raise a warning no matter the installed version of scikit-learn, and in the `DatetimeEncoder`, we don't warn at all.

In my opinion, we should be checking sklearn's version beforehand, and warn only if appropriate.

Here's a template for this behavior: 

```py
def get_feature_names(*args, **kwargs):
    if Version(sklearn.__version__) >= '1.0':
        warn(
            "Following the changes in scikit-learn 1.0, "
            "get_feature_names is deprecated. "
            "Use get_feature_names_out instead.",
            DeprecationWarning
        )
    return self.get_feature_names_out(*args, **kwargs)
```

**Comment by GaelVaroquaux** [comment]
This is done, isn't it?

**Comment by LilianBoulard** [comment]
> This is done, isn't it ?

Yes, I'm waiting for confirmation on #281, which should close this issue once merged :)
