### ISSUE TITLE
Merge examples 2 and 3

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#290]
In the light of what we talked on improving user experience:

We can add example 3 as being the last part of example 2, rather than a separate example. 
Looking at those two, I think the message is the same:
- we first explain what are dirty categories;
- we show how the encoder deals with them and how can that be interpreted.

The similarity encoder is interpreted in example 2 and the gap encoder in example 3. We may merge them?

What to do you think?

**Comment by LilianBoulard** [comment]
I agree !
You should perhaps wait for #287 to be merged before merging, as it modifies some big portions of these examples :)
