### ISSUE TITLE
`RuntimeError` should be warning

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#296]
When passing an already "clean" dataset to the `SuperVectorizer` (which is common in generic pipelines), it raises a `RuntimeError` as `No transformers could be generated!`.
The doc mentions
```
Raises
------
RuntimeError
    If no transformers could be constructed,
    usually because transformers passed do not match any column.
    To fix the issue, try passing the least amount of None as encoders.
```

First, I think the message could be reworded, as it's not very clean what "no transformers being generated" means.
Secondly, I think it should be a warning (at best), not an error.

**Comment by GaelVaroquaux** [comment]
Yes, we shouldn't error on clean datasets, just pass them along. I'm not sure that a warning is warranted.
