### ISSUE TITLE
Add all fetcher to documentation with a small docstring

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#32]

**Comment by pierreglaser** [comment]
@GaelVaroquaux not sure this is still up to date, after our discussion about merging all fetchers into a wrapper with a `str` argument. Or we can keep it, but create another issue for fetcher reformatting?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux not sure this is still up to date, after our discussion about
> merging all fetchers into a wrapper with a str argument.

It's not.
