### ISSUE TITLE
Improve doc on examples

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#324]
Some improvements on the examples may be:

- check that functions and classes are marked with the correct syntax (:class:`class_name`, :func:`function_name`)
- check that all links are working and all datasets are linked to their source (for instance, example 2 had missing link)
- try to standardize structure of examples (title, subtitle etc.) across all examples.

**Comment by LilianBoulard** [comment]
Great idea !
I started some of this work in #287, but the examples still need somewhat of an overhaul :)
