### ISSUE TITLE
Add test for `CHANGES.rst`

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#326]
I notice that on most PRs (including mine), we often forget to modify `CHANGES.rst`, however this is important.
I think we should add a small test to check that the file has been modified in the PR (compared to master).

**Comment by GaelVaroquaux** [comment]
Scikit-learn has some logic for that that we should import

**Comment by LilianBoulard** [comment]
Might also be interesting to implement some of [what has been done in GAMA](https://github.com/openml-labs/gama/blob/master/.github/workflows/changelog.yaml)

**Comment by LeoGrin** [comment]
I think this can be closed.
