### ISSUE TITLE
Use of  `if __name__ == "__main__"`:

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#334]
I don't quite understand the choice of when to use `if __name__ == "__main__":` in some files. I think we should better standardize when it is used and when not. For instance:

- I see it used in [string_distances.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/string_distances.py) and [fast_hash](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/fast_hash.py) to launch examples.
- I see it then used to launch tests in half of the tests files but then again missing in the other half ([test_datetime_encoder.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_datetime_encoder.py), [test_similarity_encoder.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_similarity_encoder.py), [test_sklearn.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_sklearn.py), [test_string_distances.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_string_distances.py), [test_target_encoder.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_target_encoder.py), [https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_utils.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/test/test_utils.py).

Should we then put it systematically in test files or not? 
Should we also remove it from the two files in the /dirty_cat folder or not?

**Comment by GaelVaroquaux** [comment]
> Should we also remove it from the two files in the /dirty_cat folder or not?

We should probably remove the corresponding lines.
