### ISSUE TITLE
Style is off for website title

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#349]
Title overlaps with the logo on my screen (1600x900).
![image](https://user-images.githubusercontent.com/33222654/190127399-201be667-9ff9-4030-9bd0-b738e43a705c.png)

**Comment by jovan-stojanovic** [comment]
Is this still relevant @LilianBoulard ?

**Comment by LilianBoulard** [comment]
> Is this still relevant @LilianBoulard ?
Yep, still an issue!

**Comment by GaelVaroquaux** [comment]
Is this fixed now @LilianBoulard  ? I tried improving a bit recently

**Comment by LilianBoulard** [comment]
Yep, definitely looks better on the current version !
