### ISSUE TITLE
Clean up our dependencies.txt files

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#380]
We have dependencies.txt files and I am not sure really what purpose they serve, as they list dependencies needed for the docs and examples, and not for dirty-cat.

We need to clean this up.

They may be needed for the binder instance that runs the examples. But the right way to do this is to create a .binder folder. Inspiration here:
https://github.com/scikit-learn/scikit-learn/tree/main/.binder

**Comment by jovan-stojanovic** [comment]
I think this is addressed partly by #365

**Comment by LilianBoulard** [comment]
Solved by #365
