### ISSUE TITLE
Rework our version matrix on the CI

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#384]
Right now the CI system used by github actions can only install two ensemble of versions of our dependencies, without the possibility of exploring a large build matrix (our matrix mostly varies the python version).
See https://github.com/dirty-cat/dirty_cat/blob/master/build_tools/github/dependencies.sh

Solution: check what scikit-learn does

Related to #380

**Comment by LilianBoulard** [comment]
Solved by #365
