### ISSUE TITLE
Website is not regenerating

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#393]
It seems that we are no longer pushing the dev docs to the corresponding repo:
https://github.com/dirty-cat/dirty-cat.github.io
(last update 8 days ago)

Our build chain is somewhat broken

**Comment by LilianBoulard** [comment]
Might be linked: on #365, there's a [CircleCI error](https://app.circleci.com/pipelines/github/dirty-cat/dirty_cat/1121) which mentions a possibly missing OAuth token.
![image](https://user-images.githubusercontent.com/33222654/197774717-7dafa474-725b-40ed-bdaa-60a64d914339.png)

**Comment by jovan-stojanovic** [comment]
This seems to be broken exactly when we changed the name from `master` to `main`?

**Comment by jovan-stojanovic** [comment]
> Might be linked: on #365, there's a [CircleCI error](https://app.circleci.com/pipelines/github/dirty-cat/dirty_cat/1121) which mentions a possibly missing OAuth token. ![image](https://user-images.githubusercontent.com/33222654/197774717-7dafa474-725b-40ed-bdaa-60a64d914339.png)

It seems that the https://github.com/dirty-cat/dirty_cat/blob/main/.circleci/config.yml file is still refering to master?

**Comment by LilianBoulard** [comment]
Maybe, yeah. I didn't rename the master at line 45 because it references a Circle branch, but I'm not sure what that is.

**Comment by jovan-stojanovic** [comment]
The errors when committing are gone, but the deployment is still not working.

**Comment by LilianBoulard** [comment]
Renaming the doc repo default branch from "master" to "main" solved the issue :)
