### ISSUE TITLE
Fetching tests raise errors at random

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#406]
As can be seen in some CI runs recently ([such as in](https://github.com/dirty-cat/dirty_cat/actions/runs/3387729832/jobs/5628850397) #365, [or on main](https://github.com/dirty-cat/dirty_cat/actions/runs/3386153511/jobs/5625193761)), the test `test_fetch_world_bank_indicator` randomly raises errors, invalidating otherwise correct code.
We should investigate what's going on.

**Comment by jovan-stojanovic** [comment]
From experience, I believe this is due to a server problem on the https://data.worldbank.org/ website. 
Actually, from what I know, when they are updating the database, it becomes often unavailable some time for download.
As we are fetching the data in some of our tests they sometimes fail.

**Comment by LilianBoulard** [comment]
That's good to know, but it's surprising then that some workers pass despite running at almost exactly the same time as the ones that fail.
