### ISSUE TITLE
Redundant ngram_similarity function name

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#440]
There are two functions that have the same name but perform on different objects:
- [ngram_similarity in _string_distances.py](https://github.com/dirty-cat/dirty_cat/blob/main/dirty_cat/_string_distances.py#L95) computes n-gram string similarity between two strings;
- [ngram_similarity in _similarity_encoder](https://github.com/dirty-cat/dirty_cat/blob/main/dirty_cat/_similarity_encoder.py#L83) does the same thing but between arrays of strings.

We should change the name of one of the two.

**Comment by LilianBoulard** [comment]
Sounds good!
