### ISSUE TITLE
Encoders do not raise parameter Value Error at initialisation

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#442]
SimilarityEncoder does not raise parameter Value Error at initialisation. So the user realise there is a problem only after trying to fit the encoder.

dirty_cat version:

Expected behavior:
```python
SimilarityEncoder(handle_unknown='blabla')
___________________________________________________________________________________
ValueError: Got handle_unknown='blabla', but expected any of {'error', 'ignore'}. 
```

Observed behavior:
```python
SimilarityEncoder(handle_unknown='blabla')
_______________________________________________
# No errors
```

**Comment by LilianBoulard** [comment]
I think that's the expected behavior, which we also observe with other encoders in the library, and even with scikit-learn's.
```
>>> ohe = OneHotEncoder(drop="blabla")
>>> ohe.fit(...)
ValueError: Wrong input for parameter `drop`. Expected 'first', 'if_binary', None or array of objects, got <class 'str'>
```

Now, I agree it would be better to check in the init as well as in the methods.

The reason this check is realized in the methods in the scikit-learn standards is to avoid this kind of behavior:
```
>>> ohe = OneHotEncoder(drop="blabla")
ValueError: Wrong input for parameter `drop`. Expected 'first', 'if_binary', None or array of objects, got <class 'str'>
>>> ohe = OneHotEncoder(drop="first")  # Valid call, doesn't raise
>>> ohe.drop = "blabla"  # Doesn't raise an error
>>> ohe.fit(...)
Raised some weird error, after the meat of the computation has been done.
```

**Comment by jovan-stojanovic** [comment]
I see, thanks for explaining this!
So we should favor checking parameters in the initialization, but beware of some errors that may occur during the fit or transform.
I agree it's better then checking them twice.

**Comment by jovan-stojanovic** [comment]
Interesting solution: https://github.com/scikit-learn/scikit-learn/pull/22722

**Comment by LilianBoulard** [comment]
Also, a library I'm very familiar with is [Pydantic](https://docs.pydantic.dev/).
Pydantic aims to validate datastructures given the python type hints. It is also possible to use their [constrained types](https://docs.pydantic.dev/usage/types/#constrained-types) for more control (the kind the sklearn PR tries to do).
It's commonly used to validate database and API values.
It's however a heavyweight library, so adding it to the requirements is quite the commitment.
