### ISSUE TITLE
`SuperVectorizer` raises a pandas `FutureWarning`

### ISSUE THREAD

**Issue by lsorber** [dirty-cat/dirty_cat#454]
I see the following pandas warning repeatedly when using the `SuperVectorizer`:

```
/.../python3.10/site-packages/dirty_cat/super_vectorizer.py:415: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
```

dirty_cat version: 0.3.0

Expected behavior: No warning

Observed behavior: Warning

**Comment by LeoGrin** [comment]
Thanks for creating an issue! I've created a PR which should remove the warning, but I haven't been able to reproduce the issue you have. Could you provide a piece of code and specifications which produces the warning?

**Comment by LilianBoulard** [comment]
Thanks for the issue. I believe it is tightly linked to the version of Pandas, could you please provide yours?

**Comment by lsorber** [comment]
This was using pandas 1.5.2.
