### ISSUE TITLE
`SuperVectorizer`'s default `low_card_cat_transformer` raises exceptions on unseen categories at test time

### ISSUE THREAD

**Issue by lsorber** [dirty-cat/dirty_cat#455]
The default `SuperVectorizer` will raise an exception on unseen categories at test time. For the default behaviour, I believe it would be more friendly to try to handle those unseen categories as best as possible (e.g. encoding them as an infrequent or missing category) instead of throwing the issue back to the user.

Workaround:
```python
ohe = OneHotEncoder(drop="if_binary", handle_unknown="infrequent_if_exist")
supervec = dirty_cat.SuperVectorizer(low_card_cat_transformer=ohe)
```

dirty_cat version: 0.3.0

Expected behavior: No exception raised for unseen categories

Observed behavior: Exception raised for unseen categories

**Comment by LeoGrin** [comment]
Thanks for the suggestion! I agree that it would be a better default. The only issue is that the `infrequent_if_exist` option requires sklearn >= 1.1, whereas we support sklearn from 0.23. One solution would be to use this default if sklearn version is greater than 1.1, but it may be confusing for users. Curious what other people think.

**Comment by LeoGrin** [comment]
I think this should be closed
