### ISSUE TITLE
`TargetEncoder`'s `handle_unkown` behavior is unclear 

### ISSUE THREAD

**Issue by DSoudis** [dirty-cat/dirty_cat#457]
The current documentation for the `TargetEncoder` seems wrong when describing the `handle_unknown` option.

> When this parameter is set to ‘ignore’ and an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros.

I assume this is some copy-paste mistake. I would expect that unknown categories are assigned the prior mean of the target variable just like missing values are in Micci-Barreca (2001). For example (page 30, first paragraph):

> If missing values have no particular relationship with the dependent then S_{o} is going to converge towards a prior probability of the target which corresponds to a "neutral" representation of the missing value

This is also possible in `R`'s `lmer` which estimates mixed effect regression models (i.e., hierachical models with Empirical Bayes shrinkage) via the `allow.new.levels` option for prediction

>  allow.new.levels .... If FALSE (default), such new values in newdata will trigger an error; if TRUE, then the prediction will use the unconditional (population-level) values for data with previously unobserved levels (or NAs).

It seems intuitive that encoding unknown categories with zero is basically saying "this category is not related to the target" while encoding them with the (unconditional )mean of the target is a more neutral statement in this setting as we are assigning the no-information rate. 

Thank you for this great library!

**Comment by jovan-stojanovic** [comment]
Hi, thanks for this issue! You are right, this is a wrong description of what the `handle_unknown` parameter does.

This is a simple, reproducible example of this scenario:

    >>> enc = TargetEncoder(handle_unknown='ignore')

    >>> X = [['male'], ['Male'], ['Female'], ['male'], ['Female']]

    >>> y = np.array([1, 2, 3, 4, 5])

    >>> enc.fit(X, y)
    TargetEncoder(handle_unknown='ignore')

    The encoder has found the following categories:

    >>> enc.categories_
    [array(['Female', 'Male', 'male'], dtype='<U6')]

    We look at the encoded categories :

    >>> X2 = [['MALE'], ['lala'], ['Female'], ['male'], ['Female']]

    >>> enc.transform(X2)
    array([[3.        ], [3.        ], [3.54545455], [2.72727273], [3.54545455]])

From this example, I can see that the `TargetEncoder` does what you pointed out (just like in Micci-Barreca (2001)).
I guess the solution is therefore just to change the docstring of the `TargetEncoder` and put what you said (and what it really does).

**Comment by DSoudis** [comment]
Great! I can close then! Thanks for looking into this
