### ISSUE TITLE
`SuperVectorizer` passes NaNs through, which causes many ML models to produce errors

### ISSUE THREAD

**Issue by lsorber** [dirty-cat/dirty_cat#458]
`SuperVectorizer` will pass through NaNs to the predictor by default. Many ML models do not inherently handle NaNs and so this means those models will fail on missing data. I think it would be nice if there would be an option to handle nonfinite numerical values.

Workaround:
```python
from sklearn.pipeline import make_union
from sklearn.impute import MissingIndicator, SimpleImputer

numerical_transformer = make_union(
    SimpleImputer(strategy="median"),
    MissingIndicator(features="missing-only", error_on_new=False)
)
supervec  = dirty_cat.SuperVectorizer(numerical_transformer=numerical_transformer)
```

Perhaps there is a way to query the predictor with something like `predictor_supports_nan = predictor._get_tags().get("allow_nan", False)` [1] and use that to determine how to handle NaNs in `SuperVectorizer`.

dirty_cat version: 0.3.0

Expected behavior: No NaNs outputted by `SuperVectorizer`

Observed behavior: NaNs outputted by `SuperVectorizer`

[1] https://scikit-learn.org/stable/developers/develop.html#estimator-tags

**Comment by GaelVaroquaux** [comment]
I think that I beg to disagree. Missing-value imputation can be an important step of the pipeline. The specific choice of an imputer is a modeling choice and typically depends on the learner used (for trees: no imputation or mean imputation, though rather not median, for most other models: iterative imputer for continuous features).

I am making this claims based on a line of research, theoretical and empirical on good ways of handling missing values in supervised learning:
- https://arxiv.org/abs/1902.06931
- https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giac013/6568998
- https://proceedings.neurips.cc/paper/2021/hash/5fe8fdc79ce292c39c5f209d734b7206-Abstract.html

**Comment by lsorber** [comment]
> I think that I beg to disagree.

What do you disagree with, specifically?

> The specific choice of an imputer is a modeling choice and typically depends on the learner used

I fully agree with that. I just think it the experience would be nicer to have things "just work" by default, and allow users to customise/improve as desired. Specifically, I would:
1. Change the default behaviour so that you can plug in any ML model (even ones that don't inherently support missing values).
2. Add the option of disabling or replacing the default imputer so that you give control to more advanced users who have a better strategy of dealing with missing values.

**Comment by GaelVaroquaux** [comment]
>     The specific choice of an imputer is a modeling choice and typically depends on the learner used

> I fully agree with that. I just think it the experience would be nicer to have things "just work" by default,

Then use a "HistGradientBoosting" model.

Once again the choice of imputation should depend on your model:
- HistGradientBoosting = no imputation
- Other tree-based models = constant imputation
- Other models = iterative imputer

This is not a choice that the SuperVectorizer can make for you.

With regards to customization, this is why we have the pipeline in scikit-learn: to be able to do this customization. It should not live in the SuperVectorizer but rather in the pipeline.

**Comment by lsorber** [comment]
> This is not a choice that the SuperVectorizer can make for you.

I don't think I understand your reasoning yet. `SuperVectorizer` already makes a lot of opinionated choices (which is a good thing to me!), so why would having an opinionated numerical transformer be a bridge too far? The upside would be that users are not faced with unexpected exceptions when plugging in their ML models. And advanced users would still be able to customise the transformers.

**Comment by GaelVaroquaux** [comment]
>     This is not a choice that the SuperVectorizer can make for you.

> I don't think I understand your reasoning yet. SuperVectorizer already makes a lot of opinionated choices (which is a good thing to me!), so why would having an opinionated numerical transformer be a bridge too far?

If you ask me an opinionated choice, my answer is simple: use HistGradientBoosting. This is what works best. For this, you need to pass the NaNs.

Reference to published benchmarks that back this opinion:
https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giac013/6568998

**Comment by lsorber** [comment]
OK, clear 👌

**Comment by GaelVaroquaux** [comment]
I think that we can close this issue?
