### ISSUE TITLE
Uninformative error in GapEncoder when n_samples < n_components

### ISSUE THREAD

**Issue by LeoGrin** [dirty-cat/dirty_cat#474]
When calling `GapEncoder` fit method with n_samples < n_components, we get the error `ValueError: n_samples=5 should be >= n_clusters=30.` raised by sklearn's kmean, which is hard to understand and fix.

dirty_cat version:
0.4.0b1

Expected behavior:
Informative error explaining what to change.

Observed behavior:
Uninformative error mentioning parameters not accessible to the user.

Steps and code to reproduce the bug:

```python
import numpy as np
from dirty_cat import SuperVectorizer
X = np.array([["officer", "manager", "lawyer", "chef", "teacher"]]).reshape(-1, 1)
sup_vec = SuperVectorizer(
        cardinality_threshold=4,
    )
sup_vec.fit_transform(X)
```

**Comment by Sohaib90** [comment]
Can I look into this?
