### ISSUE TITLE
PyPI installation of beta version fails with "FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.txt'

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#476]
I noticed that on some environments we have  this error:

`
FileNotFoundError: [Errno 2] No such file or directory: '...VERSION.txt'
`

It seems that the VERSION.txt file is not there when installing the package, which is probably due to changes we made when migrating from setup.py to setup.cfg in #365

It seems this is something already seen: https://github.com/facebookresearch/fairseq/issues/4501
The solution was to create a [MANIFEST.in file](https://github.com/lzzk/fairseq/commit/9e0ed82c15ebab325e356cd7a17184892b124d4d) that forces the VERSION.txt (`include VERSION.txt`) version to be included. I don't know if this is the right way to go.

We should probably correct this and publish a beta version 2 to see if everything goes well.

**Comment by GaelVaroquaux** [comment]
> The solution was to create a MANIFEST.in file that forces the VERSION.txt (include VERSION.txt) version to be included.

Either this, or use "package_data" keyword: https://docs.python.org/3/distutils/setupscript.html#installing-package-data

**Comment by jovan-stojanovic** [comment]
> The solution was to create a [MANIFEST.in file](https://github.com/lzzk/fairseq/commit/9e0ed82c15ebab325e356cd7a17184892b124d4d) that forces the VERSION.txt (include VERSION.txt) version to be included.

As we moved from setup.py to setuptools, confirmation in the setuptools docs:
https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#controlling-files-in-the-distribution
