### ISSUE TITLE
ArrayMemoryError when doing fuzzy_join on large tables

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#511]
See here: https://output.circle-artifacts.com/output/job/bf578908-79c7-41a7-a604-50fc290f7976/artifacts/0/doc/auto_examples/06_ken_embeddings_example.html#merging-the-entities
The following memory error appears when we apply a fuzzy_join:
```
Traceback (most recent call last):
...
    out = self._process_toarray_args(order, out)
  File "/home/circleci/project/miniconda/envs/testenv/lib/python3.8/site-packages/scipy/sparse/_base.py", line 1298, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 129. GiB for an array with shape (16514, 1048576) and data type float64
```
I think I identified the source of the error:
- when we use the [HashingVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.HashingVectorizer.html) to transform the categories,  an array of shape (number_of_categories, 2 ** 18) is created by default. This is a sparse matrix.
- Then, when we try to find the nearest neighbors using this matrix, we have to transform it to a dense one. This creates this memory error.

I will create a PR and start working on the solution. I think it should be easy to fix, there is a parameter `n_features` of the  [HashingVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.HashingVectorizer.html) that regulates the size (2 ** 17 instead of 2 ** 18) seems to work. However, I still want to inspect if this does not impact the accuracy of the join.

**Comment by jjerphan** [comment]
Hi @jovan-stojanovic, what is the version of joblib you are using?

**Comment by jjerphan** [comment]
https://github.com/dirty-cat/dirty_cat/pull/513 should minimally fix it.
