### ISSUE TITLE
Automatic column vectorizer depending on the column structure

### ISSUE THREAD

**Issue by pcerda** [dirty-cat/dirty_cat#54]
Automatically select the type of encoder for a given column depending on its structure:

- If the column type is 'float' or 'int', pass through.

- If the column is type is 'categorical', select the encoder depending on the cardinality 'k' of the variable. For example: If k<=20, select one-hot encoding; if not, select similarity encoding.

**Comment by GaelVaroquaux** [comment]
As a side note, we cannot name this object "AutoEncoder", as an autoencoder is already a well-identified concept in machine learning that differs quite strongly from what we do here.

Maybe, as a proposed name: DataFrameEncoder

**Comment by amy12xx** [comment]
Adding some more to the mix: AutoSelectEncoder, BestEncoder and MetaEncoder.

**Comment by GaelVaroquaux** [comment]
This has been implemented.
