### ISSUE TITLE
Expose the seed of the kmeans

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#69]
We need to expose the seed of the kmeans in the similarity encoder, to make the pipelines fully reproducible. For this, we need to add a "random_state" option to the similarity encoder, as in many scikit-learn models, and pass it to kmeans.

**Comment by mcuny** [comment]
Is the passed option an integer used as a seed to build a numpy RandomState instance or do we just pass the integer to k-means? (asking because both are possible in the documentation)

**Comment by GaelVaroquaux** [comment]
I think that:

* in fit we use check_random_state to create self.random_state_ from self.random_state
* we pass self.random_state_ to KMeans

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by GaelVaroquaux** [comment]
Closing as fixed
